name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c877c6ff4ed43408813aa1cb77424ce28e651f483c1f0e3df2f80a035f7ef090"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
