name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97ba082fc0c99ceb420f510ee085874fdbfe3e25ca5599e616c6793576383c22"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
