name = "Arose-MTR Modpack Installer"
author = "KingRanger17"
version = "1.0.24"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cb2c06bd64f653d8fd1ef6ea98a22f981c7a1a829eb910c1ea27597b8337a51d"

[versions]
fabric = "0.18.4"
minecraft = "1.20.4"
